src/Entity/Admin.php
<?php

namespace App\Entity;

use App\Repository\AdminRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdminRepository::class)]
class Admin extends Users
{



    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;
    #[ORM\Column(type: "string", length: 255)]
    private ?string $Email = null;

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(?string $Email): void
    {
        $this->Email = $Email;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }
}

src/Entity/Adminbyplace.php
<?php

namespace App\Entity;

use App\Repository\AdminbyplaceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdminbyplaceRepository::class)]
class Adminbyplace extends Users
{
    /**
     * @var Collection<int, Activity>
     */
    #[ORM\OneToMany(targetEntity: Activity::class, mappedBy: 'adminbyplace')]
    private Collection $activities;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * @var Collection<int, Participation>
     */
    #[ORM\OneToMany(targetEntity: Participation::class, mappedBy: 'adminByPlace')]
    private Collection $participationsAdminByPlace;

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

    public function __construct()
    {
        $this->activities = new ArrayCollection();
        $this->participationsAdminByPlace = new ArrayCollection();
    }

    /**
     * @return Collection<int, Activity>
     */
    public function getActivities(): Collection
    {
        return $this->activities;
    }

    public function addActivity(Activity $activity): static
    {
        if (!$this->activities->contains($activity)) {
            $this->activities->add($activity);
            $activity->setAdminbyplace($this);
        }

        return $this;
    }

    public function removeActivity(Activity $activity): static
    {
        if ($this->activities->removeElement($activity)) {
            // set the owning side to null (unless already changed)
            if ($activity->getAdminbyplace() === $this) {
                $activity->setAdminbyplace(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Participation>
     */
    public function getParticipationsAdminByPlace(): Collection
    {
        return $this->participationsAdminByPlace;
    }

    public function addParticipationsAdminByPlace(Participation $participationsAdminByPlace): static
    {
        if (!$this->participationsAdminByPlace->contains($participationsAdminByPlace)) {
            $this->participationsAdminByPlace->add($participationsAdminByPlace);
            $participationsAdminByPlace->setAdminByPlace($this);
        }

        return $this;
    }

    public function removeParticipationsAdminByPlace(Participation $participationsAdminByPlace): static
    {
        if ($this->participationsAdminByPlace->removeElement($participationsAdminByPlace)) {
            // set the owning side to null (unless already changed)
            if ($participationsAdminByPlace->getAdminByPlace() === $this) {
                $participationsAdminByPlace->setAdminByPlace(null);
            }
        }

        return $this;
    }
}

src/Controller/AdminByPlaceController.php
<?php

namespace App\Controller;

use App\Entity\Activity;
use App\Entity\Adminbyplace;
use App\Entity\Participation;
use App\Form\ActivityType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
#[Route('/adminbp')]
class AdminByPlaceController extends AbstractController
{

    private $entityManager;
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/', name: 'app_adminplace')]
    public function index(): Response
    {

        $activities = $this->entityManager->getRepository(Activity::class)->findBy(['adminbyplace' => $this->getUser()]);
        return $this->render('admin_by_place/index.html.twig', [
            'controller_name' => 'adminplaceController',
            'activities' => $activities,
        ]);
    }

    #[Route('/participate/{userId}/{activityId}/participations', name: 'app_participations_donors')]
    public function getParticipations($userId ,$activityId )
    {
        $userIdAdmin = $this->entityManager->getRepository(Adminbyplace::class)->findOneBy(['user' => $userId]);
        $activities = $this->entityManager->getRepository(Activity::class)->findBy(['adminbyplace' => $userIdAdmin, 'id' => $activityId]);

        $participations = [];
        foreach ($activities as $activity) {
            $activityParticipations = $this->   entityManager->getRepository(Participation::class)->findBy(['activity' => $activity, 'confirmedByNurse' => 1]);
            if (empty($activityParticipations)) {
                error_log('No participations found for activity with id: ' . $activity->getId());
            }
            $participations = array_merge($participations, $activityParticipations);
        }

        $donors = [];
        foreach ($participations as $participation) {
            $donor = $participation->getDonor();
            if ($donor === null) {
                error_log('No donor found for participation with id: ' . $participation->getId());
            } else {
                $donors[] = $donor;
            }
        }

        return $this->render('admin_by_place/participations.html.twig', [
            'donors' => $donors,
        ]);
    }
    #[Route('/donor/{id}/validate', name: 'donor_validate')]
    public function validateDonor($id)
    {
        $partcipation = $this->entityManager->getRepository(Participation::class)->find($id);
        if ($partcipation) {
            $partcipation->setConfirmedByAdmin(true);
            $this->entityManager->flush();
        }

        return $this->redirectToRoute('app_participations_donors', ['userId' => $partcipation->getAdminByPlace()->getUser()->getId(), 'activityId' => $partcipation->getActivity()->getId()]);

    }
    #[Route('/donor/{id}/invalidate', name: 'donor_invalidate')]
    public function invalidateDonor($id)
    {
        $partcipation = $this->entityManager->getRepository(Participation::class)->find($id);
        if ($partcipation) {
            $partcipation->setConfirmedByAdmin(false);
            $this->entityManager->flush();
        }

        return $this->redirectToRoute('app_participations_donors', ['userId' => $partcipation->getAdminByPlace()->getUser()->getId(), 'activityId' => $partcipation->getActivity()->getId()]);
    }

    #[Route('/activity/new', name: 'app_activity_new')]
    public function addActivity(Request $request): Response
    {
        $activity = new Activity();
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $loggedInUser = $this->getUser();

            // Fetch the Adminbyplace entity that corresponds to the logged in user
            $adminbyplace = $this->entityManager->getRepository(Adminbyplace::class)->findOneBy(['user' => $loggedInUser]);

            if ($adminbyplace) {
                // Set the adminbyplace field of the Activity with the fetched Adminbyplace entity
                $activity->setAdminbyplace($adminbyplace);

                // Persist and flush the Activity entity
                $this->entityManager->persist($activity);
                $this->entityManager->flush();

                return $this->redirectToRoute('app_adminplace');
            } else {
                // Handle the case where the logged in user is not an Adminbyplace
                // Redirect to a different route or show an error message
            }
        }

        return $this->render('admin_by_place/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/certificate/approve', name: 'app_certificate_approve')]
    public function approveCertificate(Request $request): Response
    {
        $approvedParticipations = $this->entityManager->getRepository(Participation::class)->findBy(['approvedByNurse' => true]);

        foreach ($approvedParticipations as $participation) {
            $donors = $participation->getDonor();

            foreach ($donors as $donor) {
                $isBloodGood = $this->validateBlood($donor->getBloodType());

                $participation->setApproved($isBloodGood);

                $this->entityManager->persist($participation);
            }
        }

        $this->entityManager->flush();

        return $this->redirectToRoute('certificate_index');
    }

    private function validateBlood($blood)
    {
        return (bool)random_int(0, 1);
    }
}

templates/admin_by_place/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AdminByPlaceController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>/home/naceur/Desktop/GithubProjects/BloodDonationManager/src/Controller/AdminByPlaceController.php</code></li>
        <li>Your template at <code>/home/naceur/Desktop/GithubProjects/BloodDonationManager/templates/admin_by_place/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/admin_by_place/new.html.twig
{# templates/activity/new.html.twig #}

{% extends 'base.html.twig' %}
{% block activityadminbyplace %}
{% endblock activityadminbyplace %}
{% block title %}New Activity{% endblock %}

{% block body %}
    <h1>Create new Activity</h1>

    {{ form_start(form) }}

    {{ form_row(form.date, {'attr': {'class': 'form-control'}}) }}
    {{ form_row(form.status, {'attr': {'class': 'form-control'}}) }}
    {{ form_row(form.nameActivity, {'attr': {'class': 'form-control'}}) }}
    {{ form_row(form.description, {'attr': {'class': 'form-control'}}) }}
    {{ form_row(form.nurses, {'attr': {'class': 'form-control'}}) }}


    <button class="btn btn-primary">Save</button>

    {{ form_end(form) }}
{% endblock %}

templates/admin_by_place/participations.html.twig
{% extends 'base.html.twig' %}
{% block activityadminbyplace %}
{% endblock activityadminbyplace %}
{% block body %}

    <h1>Donors who participated in activities</h1>

    {% if donors is not empty %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Blood Type</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for donor in donors %}
                <tr>
                    <td>{{ donor.getFirstName() }}</td>
                    <td>{{ donor.getLastName() }}</td>
                    <td>{{ donor.email }}</td>
                    <td>{{ donor.getBloodType() }}</td>
                    <td>
                        <a href="{{ path('donor_validate', {'id': donor.participation.id}) }}" class="btn btn-success">Validate</a>
                        <a href="{{ path('donor_invalidate', {'id': donor.participation.id}) }}" class="btn btn-danger">Invalidate</a>
                    </td>
                    <td></td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No donors found.</p>
    {% endif %}
{% endblock %}